name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - version: latest
          - version: latest-ubuntu
          - version: 2022-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/mssql-server
          tags: |
            type=raw,value=${{ matrix.version }}

      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ matrix.version }}
          cache-from: type=gha,scope=build-${{ matrix.version }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.version }}
